services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  streamlit-frontend:
    build: ./streamlit-frontend
    ports:
      - 8501:8501
    depends_on:
      - redis
      - publisher

  publisher:
    build: ./publisher
    depends_on:
      - redis

  subscriber:
    build: ./subscriber
    depends_on:
      - redis
      - publisher
    restart: on-failure
    ports:
      - 8000:8000
  